selected_ids = [
  "django__django-11400",
  "django__django-15161",
  "matplotlib__matplotlib-21568",
  "django__django-15930",
  "sympy__sympy-20590",
  "django__django-14559",
  "django__django-11211",
  "django__django-16082",
  "sympy__sympy-16792",
  "scikit-learn__scikit-learn-12585",
  "django__django-15252",
  "sympy__sympy-24661",
  "psf__requests-5414",
  "sphinx-doc__sphinx-8265",
  "sympy__sympy-23534",
  "pytest-dev__pytest-7236",
  "django__django-13569",
  "sphinx-doc__sphinx-11510",
  "django__django-11477",
  "django__django-15128",
  "django__django-14238",
  "django__django-16612",
  "django__django-16877",
  "django__django-13513",
  "django__django-16667",
  "psf__requests-1724",
  "sympy__sympy-17318",
  "sympy__sympy-13852",
  "django__django-12050",
  "sympy__sympy-21930",
  "sphinx-doc__sphinx-9711",
  "django__django-15525",
  "django__django-14539",
  "django__django-11138",
  "django__django-11451",
  "django__django-13837",
  "scikit-learn__scikit-learn-14629",
  "django__django-16662",
  "sphinx-doc__sphinx-7757",
  "sphinx-doc__sphinx-8056",
  "django__django-15561",
  "scikit-learn__scikit-learn-10908",
  "django__django-11555",
  "django__django-16950",
  "django__django-12858",
  "pytest-dev__pytest-7432",
  "psf__requests-2317",
  "django__django-11119",
  "django__django-15127",
  "sphinx-doc__sphinx-10614",
  "django__django-16485",
  "django__django-16642",
  "django__django-11964",
  "django__django-17029",
  "sympy__sympy-20428",
  "sympy__sympy-22714",
  "django__django-16255",
  "django__django-14349",
  "django__django-13401",
  "sympy__sympy-15976",
  "django__django-16333",
  "sympy__sympy-20801",
  "sympy__sympy-14531",
  "django__django-13410",
  "astropy__astropy-13453",
  "django__django-15368",
  "scikit-learn__scikit-learn-25747",
  "mwaskom__seaborn-3069",
  "django__django-14376",
  "matplotlib__matplotlib-24177",
  "sympy__sympy-21612",
  "sympy__sympy-14976",
  "sphinx-doc__sphinx-9229",
  "sympy__sympy-16450",
  "django__django-14007",
  "scikit-learn__scikit-learn-13124",
  "astropy__astropy-14995",
  "sphinx-doc__sphinx-10449",
  "pylint-dev__pylint-4970",
  "django__django-14608",
  "django__django-14351",
  "django__django-11885",
  "astropy__astropy-7336",
  "astropy__astropy-8707",
  "matplotlib__matplotlib-24870",
  "scikit-learn__scikit-learn-25931",
  "django__django-11815",
  "pytest-dev__pytest-8399",
  "sympy__sympy-24443",
  "sympy__sympy-12481",
  "django__django-12125",
  "sympy__sympy-19040",
  "django__django-13128",
  "django__django-14434",
  "django__django-14771",
  "django__django-15280",
  "sympy__sympy-19954",
  "astropy__astropy-14598",
  "django__django-12406",
  "sphinx-doc__sphinx-8551",
]
